# Generated by Django 5.1 on 2024-09-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role_customuser_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='distance_office',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in miles', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='time_office',
            field=models.IntegerField(blank=True, help_text='Travel time to office in minutes (e.g. 90 for 1 hour 30 minutes)', null=True),
        ),
    ]
