# Generated by Django 5.1 on 2024-11-05 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_all_employees', 'Can view all employees'), ('can_manage_employees', 'Can manage employees')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='second_approver',
            field=models.ForeignKey(blank=True, help_text='Second approver for timesheet entries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approval_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_office',
            field=models.IntegerField(blank=True, help_text='Travel time to office in minutes', null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
