# Generated by Django 5.1 on 2024-12-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_options_customuser_second_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_role_title',
            field=models.CharField(blank=True, help_text="Custom role title when 'Other' is selected", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Field Technician', 'Field Technician'), ('Lab Technician', 'Lab Technician'), ('Office Support', 'Office Support'), ('Operations Support', 'Operations Support'), ('Supervisor', 'Supervisor'), ('Other', 'Other')], default='Field Technician', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationinvitation',
            name='role',
            field=models.CharField(choices=[('Field Technician', 'Field Technician'), ('Lab Technician', 'Lab Technician'), ('Office Support', 'Office Support'), ('Operations Support', 'Operations Support'), ('Supervisor', 'Supervisor'), ('Other', 'Other')], max_length=50),
        ),
    ]
