# Generated by Django 5.1 on 2024-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='comments',
            field=models.TextField(blank=True, help_text='Any additional notes or comments for this time entry.', null=True),
        ),
    ]
