# Generated by Django 5.1 on 2024-10-31 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_alter_laborcode_labor_code_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitter_comments', models.TextField(blank=True)),
                ('reviewer_comments', models.TextField(blank=True)),
            ],
            options={
                'permissions': [('can_approve_timesheet', 'Can approve timesheet entries'), ('can_reject_timesheet', 'Can reject timesheet entries')],
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['activity_arrive_time']},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['time_entry', 'activity_arrive_time'], name='job_timeentry_arrive_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['time_entry', 'activity_leave_time'], name='job_timeentry_leave_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_number'], name='job_number_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['labor_code'], name='job_labor_code_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['time_entry', 'job_number', 'activity_arrive_time'], name='job_entry_num_time_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'date'], name='timesheet_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['date'], name='timesheet_date_only_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['start_time'], name='timesheet_start_time_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['end_time'], name='timesheet_end_time_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['hours_for_the_day'], name='timesheet_hours_day_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['total_miles'], name='timesheet_total_miles_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['miles_to_be_paid'], name='timesheet_paid_miles_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['hours_to_be_paid'], name='timesheet_paid_hours_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['start_location'], name='timesheet_start_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['end_location'], name='timesheet_end_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'date', 'start_time'], name='timesheet_user_date_time_idx'),
        ),
        migrations.AddField(
            model_name='timeentryapproval',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentryapproval',
            name='time_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='timesheets.timeentry'),
        ),
    ]
