# Generated by Django 5.1 on 2024-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_timeentry_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='company_vehicle_used',
            field=models.BooleanField(choices=[(True, 'Company Vehicle'), (False, 'Personal Vehicle')], default=False, verbose_name='Vehicle Used'),
        ),
    ]
