# Generated by Django 5.1 on 2024-09-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_alter_laborcode_labor_code_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laborcode',
            options={'ordering': ['laborcode']},
        ),
    ]
