# Generated by Django 5.1 on 2024-09-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_timeentry_company_vehicle_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='activity_arrive_time',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='activity_leave_time',
        ),
    ]
