# Generated by Django 5.1 on 2024-09-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_alter_laborcode_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laborcode',
            options={'ordering': ['id']},
        ),
    ]
