# Generated by Django 5.1 on 2024-09-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_alter_laborcode_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laborcode',
            options={},
        ),
        migrations.AlterField(
            model_name='laborcode',
            name='laborcode',
            field=models.IntegerField(unique=True),
        ),
    ]
