# Generated by Django 5.1 on 2024-11-05 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_approvalnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentryapproval',
            options={'permissions': [('can_first_approve', 'Can do first approval of timesheet entries'), ('can_second_approve', 'Can do second approval of timesheet entries'), ('can_reject_timesheet', 'Can reject timesheet entries')]},
        ),
        migrations.RenameField(
            model_name='timeentryapproval',
            old_name='reviewed_at',
            new_name='first_reviewed_at',
        ),
        migrations.RenameField(
            model_name='timeentryapproval',
            old_name='reviewer_comments',
            new_name='first_reviewer_comments',
        ),
        migrations.RemoveField(
            model_name='timeentryapproval',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='timeentryapproval',
            name='first_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_reviewed_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentryapproval',
            name='second_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentryapproval',
            name='second_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_reviewed_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentryapproval',
            name='second_reviewer_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeentryapproval',
            name='status',
            field=models.CharField(choices=[('pending_first', 'Pending First Approval'), ('pending_second', 'Pending Second Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_first', max_length=20),
        ),
    ]
