# Generated by Django 5.1 on 2024-09-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_remove_timeentry_activity_arrive_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='activity_arrive_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='activity_leave_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
