# Generated by Django 5.1 on 2024-09-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_alter_laborcode_options_alter_laborcode_laborcode'),
    ]

    operations = [
    ]
