# Generated by Django 5.1 on 2024-11-05 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_alter_timeentryapproval_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentryapproval',
            options={},
        ),
        migrations.AlterField(
            model_name='timeentryapproval',
            name='first_reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeentryapproval',
            name='second_reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
