# Generated by Django 5.1 on 2024-09-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_timeentry_activity_arrive_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='activity_arrive_time',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='activity_leave_time',
        ),
    ]
