# Generated by Django 5.1 on 2024-11-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0008_approvalnotification_notification_type_and_more'),
        ('timesheets', 'add_notification_type'),
    ]

    operations = [
    ]
