# Generated by Django 5.1 on 2024-11-07 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0010_timeentryapproval_reviewed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentryapproval',
            name='reviewed_by',
        ),
        migrations.CreateModel(
            name='TimeEntryApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_first', 'Pending First Approval'), ('pending_second', 'Pending Second Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_first_review', models.BooleanField(default=False)),
                ('is_second_review', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('time_entry_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='timesheets.timeentryapproval')),
            ],
            options={
                'verbose_name_plural': 'Time Entry Approval Histories',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
