# Generated by Django 5.1 on 2024-11-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0011_remove_timeentryapproval_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='client_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='project_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
