# Generated by Django 5.1 on 2024-11-27 21:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0014_timeentryapproval_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvalnotification',
            unique_together={('time_entry_approval', 'notification_type', 'recipient')},
        ),
    ]
