# Generated by Django 5.1 on 2024-11-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_add_unique_constraint_to_approval_notification'),
        ('timesheets', '0015_alter_approvalnotification_unique_together'),
    ]

    operations = [
    ]
