# Generated by Django 5.1 on 2024-11-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0016_merge_20241127_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalnotification',
            options={'ordering': ['-created_at']},
        ),
    ]
