# Generated by Django 5.1 on 2024-12-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0017_alter_approvalnotification_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_rate', models.DecimalField(decimal_places=2, default=0.55, help_text='Rate per mile in dollars', max_digits=5)),
                ('vehicle_allowance', models.DecimalField(decimal_places=2, default=0.0, help_text='Daily vehicle allowance in dollars', max_digits=6)),
                ('effective_date', models.DateField(auto_now_add=True, help_text='Date these rates become effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_date'],
                'get_latest_by': 'effective_date',
            },
        ),
    ]
