# Generated by Django 5.1 on 2024-12-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0021_job_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='duration',
        ),
    ]
